# Generated by Django 5.0 on 2024-01-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrainfo', '0002_department_appointment_doctor_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
