# Generated by Django 5.0 on 2024-01-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrainfo', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
