# Generated by Django 5.0 on 2023-12-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
