# Generated by Django 5.0.2 on 2024-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
