# Generated by Django 5.0.2 on 2024-02-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0006_alter_chat_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
